/**
 * Cloudinary Media Helper Utility
 * Provides performance optimization for both videos and images using Cloudinary.
 * Integrates automatic format adaptation (f_auto), automatic compression (q_auto),
 * dynamic resizing, and a robust local fallback system when Cloudinary is not configured.
 */

const CLOUD_NAME = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME;
const IS_CONFIGURED = CLOUD_NAME && CLOUD_NAME !== 'your_cloudinary_cloud_name';

/**
 * Mapping of local video assets to their Cloudinary public IDs.
 * Replace these public IDs with the ones you get after uploading the videos to your Cloudinary Media Library.
 * We group them under a folder 'urbancode' for clean organization.
 */
export const HOMEPAGE_VIDEO_MAP = {
    "/videos/testimonial1.mp4": "urbancode/testimonial1",
    "/videos/testimonial2.mp4": "urbancode/testimonial2",
    "/videos/testimonial3.mp4": "urbancode/testimonial3",
    "/videos/kids-testimonial-video1.mp4": "urbancode/kids-testimonial-video1"
};

/**
 * Generates an optimized Cloudinary delivery URL for a video.
 * Uses automatic compression and format negotiation.
 * 
 * @param {string} src - The local path or Cloudinary public ID.
 * @param {object} options - Custom transformations.
 * @returns {string} - The optimized URL or local fallback path.
 */
export function getOptimizedVideoUrl(src, options = {}) {
    if (!src) return '';

    // Check if Cloudinary is configured
    if (!IS_CONFIGURED) {
        return src; // Fallback to local path
    }

    // Resolve the public ID (check if mapped or use direct public ID)
    const publicId = HOMEPAGE_VIDEO_MAP[src] || src;

    // If it's already an absolute external URL and not a Cloudinary asset, return as-is
    if (publicId.startsWith('http') && !publicId.includes('cloudinary.com')) {
        return publicId;
    }

    // Prepare transformations
    const quality = options.quality || 'q_auto:good'; // q_auto:good balances quality and extreme size savings
    const format = options.format || 'f_auto';
    const rawTransformations = options.transformations ? `,${options.transformations}` : '';
    
    // Construct Cloudinary URL for video
    // Format: https://res.cloudinary.com/<cloud_name>/video/upload/<transformations>/v<version>/<public_id>
    return `https://res.cloudinary.com/${CLOUD_NAME}/video/upload/${format},${quality}${rawTransformations}/${publicId}`;
}

/**
 * Generates a thumbnail/poster image URL from a Cloudinary video.
 * Extremely useful for setting poster frame placeholders without loading the video.
 * 
 * @param {string} src - The local path or Cloudinary public ID.
 * @param {object} options - Options including time position (default 0.5s).
 * @returns {string} - The poster image URL or fallback.
 */
export function getVideoPosterUrl(src, options = {}) {
    if (!src) return '';

    if (!IS_CONFIGURED) {
        // Return a default mock or local placeholder image if local fallback
        return options.fallbackPoster || '';
    }

    const publicId = HOMEPAGE_VIDEO_MAP[src] || src;

    if (publicId.startsWith('http') && !publicId.includes('cloudinary.com')) {
        return options.fallbackPoster || '';
    }

    const time = options.time !== undefined ? `so_${options.time}` : 'so_0.5';
    const quality = options.quality || 'q_auto';
    const format = options.format || 'f_auto';
    const width = options.width ? `w_${options.width}` : 'w_800'; // Default width to avoid massive image sizes
    const crop = options.crop || 'c_limit';

    // Video thumbnails are generated by requesting the asset as an image
    // Format: https://res.cloudinary.com/<cloud_name>/video/upload/<transformations>/<public_id>.jpg
    return `https://res.cloudinary.com/${CLOUD_NAME}/video/upload/${format},${quality},${time},${width},${crop}/${publicId}.jpg`;
}

/**
 * Generates an optimized Cloudinary delivery URL for an image.
 * 
 * @param {string} src - Local image path or Cloudinary public ID.
 * @param {object} options - Responsive sizing and optimization options.
 * @returns {string} - The optimized image URL or local path.
 */
export function getOptimizedImageUrl(src, options = {}) {
    if (!src) return '';

    if (!IS_CONFIGURED) {
        return src;
    }

    // Mappings for key homepage images can be added here if needed
    const publicId = src;

    if (publicId.startsWith('http') && !publicId.includes('cloudinary.com')) {
        return publicId;
    }

    const quality = options.quality || 'q_auto';
    const format = options.format || 'f_auto';
    const width = options.width ? `w_${options.width}` : '';
    const height = options.height ? `h_${options.height}` : '';
    const crop = options.crop || (width || height ? 'c_fill' : '');

    const transformations = [format, quality, width, height, crop].filter(Boolean).join(',');

    return `https://res.cloudinary.com/${CLOUD_NAME}/image/upload/${transformations}/${publicId}`;
}
