const eventsData = [
  {
    id: 1,
    type: "SEMINAR",
    color: "#16a34a",
    iconName: "Bot",
    date: "SEPTEMBER 16, 2025",
    title: "Emerging Trends in Business AI",
    desc: "Students explored how AI is reshaping modern business workflows, decision-making, and automation across industries.",
    attendees: "180+",
    venue: "St Joseph's Engineering",
    status: "Completed",
  },
  {
    id: 2,
    type: "WORKSHOP",
    color: "#1d4ed8",
    iconName: "Trophy",
    date: "APRIL 21, 2025",
    title: "BB Grand Meet Up 2025",
    desc: "A complete guide for final-year students to prepare for interviews, improve resumes, and approach companies effectively.",
    attendees: "150+",
    venue: "Ramada Plaza, Guindy",
    status: "Completed",
  },
  {
    id: 3,
    type: "SEMINAR",
    color: "#7c3aed",
    iconName: "Lightbulb",
    date: "JUNE 15, 2024",
    title: "Workshop & Seminars",
    desc: "Industry experts shared insights on skill trends, future job roles, and the importance of personal branding in careers.",
    attendees: "200+",
    venue: "SIMATS Engineering",
    status: "Completed",
  },
  {
    id: 4,
    type: "BOOTCAMP",
    color: "#16a34a",
    iconName: "Rocket",
    date: "MARCH 19, 2024",
    title: "Urbancode AI Workshop",
    desc: "Students worked on live startup ideas with mentors guiding them through business models, pitch decks, and funding basics.",
    attendees: "90+",
    venue: "Kings Engineering College",
    status: "Completed",
  },
  {
    id: 5,
    type: "HACKATHON",
    color: "#b45309",
    iconName: "Smartphone",
    date: "COMING SOON — 2026",
    title: "Mobile App Hackathon",
    desc: "24-hour hackathon where teams build and deploy real mobile apps using Flutter and React Native with live mentorship.",
    attendees: null,
    venue: "Registration Open",
    status: "Upcoming",
  },
  {
    id: 6,
    type: "WORKSHOP",
    color: "#1e293b",
    iconName: "Cloud",
    date: "COMING SOON — 2026",
    title: "Cloud & DevOps Summit",
    desc: "Hands-on AWS, Docker, and Kubernetes workshop with industry professionals for practical cloud deployment skills.",
    attendees: null,
    venue: "Registration Open",
    status: "Upcoming",
  },
];

export default eventsData;